apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: your-microservice
spec:
  hosts:
    - yourdomain.com
  gateways:
    - your-gateway
  http:
    - route:
        - destination:
            host: your-microservice-service
            port:
              number: 80
